spring:
  h2:
    console:
      enabled: true
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  
    properties:
      hibernate.format_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/demoapp
    username: sa
    password:

